version: '3.8'

services:
  # Serviço do Backend (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"  # Porta externa 8000 para o backend Laravel
    volumes:
      - ./backend:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: todo_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Serviço do Frontend (Nuxt.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt_frontend
    ports:
      - "3000:3000"  # Porta externa 3000 para o frontend Nuxt.js
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - HOST=0.0.0.0
    networks:
      - app-network

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  # Serviço do PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"  # Porta externa 8080 para o PHPMyAdmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
